function esc(s){return String(s??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));}
export function renderReport(a,id=""){
const s=a.summary||{};
const dims=(a.dimensions||[]).map(c=>"<tr><td>"+esc(c.label)+"</td><td><b>"+esc(c.status)+"</b></td><td>"+esc((c.evidence||[]).join(" "))+"</td></tr>").join("");
const rows=(a.controls||[]).map(c=>"<tr><td>"+esc(c.label)+"</td><td><b>"+esc(c.status)+"</b></td><td>"+esc((c.evidence||[]).join(" "))+"</td></tr>").join("");
const follow=(a.followUps||[]).map(x=>"<li>"+esc(x)+"</li>").join("");
const questions=(a.decisionQuestions||[]).map(x=>"<li>"+esc(x)+"</li>").join("");
const limits=(a.limitations||[]).map(x=>"<li>"+esc(x)+"</li>").join("");
return "<!doctype html><html><head><meta charset=\"utf-8\"><title>Vendor Assessment Report</title><style>body{font-family:Arial,sans-serif;max-width:900px;margin:40px auto;padding:0 20px;color:#172033}h1{font-size:36px}.meta{color:#596579}.box{border:1px solid #dce2eb;border-radius:12px;padding:18px;margin:18px 0}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.metric{background:#f5f7fa;padding:14px;border-radius:8px}.metric b{font-size:24px}table{width:100%;border-collapse:collapse}td,th{padding:10px;border-bottom:1px solid #e5e9ef;text-align:left;vertical-align:top}.print{margin-bottom:20px}button{padding:10px 15px;border:0;border-radius:7px}@media print{.print{display:none}}</style></head><body><div class=\"print\"><button onclick=\"print()\">Print / Save as PDF</button></div><h1>Vendor Assessment Report</h1><p class=\"meta\">Generated "+esc(a.generatedAt||new Date().toISOString())+(id?" · Assessment "+esc(id):"")+"</p><div class=\"box\"><h2>"+esc(a.vendor?.name||"Unspecified vendor")+"</h2><p>"+esc(a.vendor?.url||"")+"</p><p><b>Framework:</b> "+esc(a.framework||"Evidence-first due diligence")+"</p></div><div class=\"grid\"><div class=\"metric\">Risk signal<br><b>"+esc(s.riskLevel)+"</b></div><div class=\"metric\">Supported<br><b>"+(s.supported??0)+"</b></div><div class=\"metric\">Partial<br><b>"+(s.partial??0)+"</b></div><div class=\"metric\">Unknown<br><b>"+(s.unknown??0)+"</b></div></div><div class=\"box\"><h2>Due-diligence dimensions</h2><table><tr><th>Dimension</th><th>Status</th><th>Evidence</th></tr>"+dims+"</table></div><div class=\"box\"><h2>Control evidence</h2><table><tr><th>Control</th><th>Status</th><th>Evidence</th></tr>"+rows+"</table></div><div class=\"box\"><h2>Follow-up questions</h2><ul>"+follow+"</ul></div><div class=\"box\"><h2>Decision record</h2><ul>"+questions+"</ul></div><div class=\"box\"><h2>Limitations</h2><ul>"+limits+"</ul></div></body></html>";
}
