import pg from "pg";
const {Pool}=pg;
let pool=null;
let initPromise=null;
function getPool(){if(!process.env.DATABASE_URL)return null;if(!pool)pool=new Pool({connectionString:process.env.DATABASE_URL,max:5,idleTimeoutMillis:10000,connectionTimeoutMillis:5000});return pool;}
export async function initStorage(){const p=getPool();if(!p)return {enabled:false,reason:"DATABASE_URL not configured"};if(initPromise)return initPromise;initPromise=(async()=>{await p.query(`CREATE TABLE IF NOT EXISTS assessments(id UUID PRIMARY KEY,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),vendor_name TEXT NOT NULL,vendor_url TEXT,evidence TEXT NOT NULL,result JSONB NOT NULL);CREATE TABLE IF NOT EXISTS leads(id UUID PRIMARY KEY,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),name TEXT,email TEXT NOT NULL,company TEXT,role TEXT,source TEXT,assessment_id UUID,metadata JSONB NOT NULL DEFAULT '{}'::jsonb);CREATE INDEX IF NOT EXISTS assessments_created_at_idx ON assessments(created_at DESC);CREATE INDEX IF NOT EXISTS leads_created_at_idx ON leads(created_at DESC);`);return {enabled:true};})().catch(err=>{initPromise=null;throw err});return initPromise;}
export async function saveAssessment(a){const p=getPool();if(!p)return null;const id=crypto.randomUUID();await p.query("INSERT INTO assessments(id,vendor_name,vendor_url,evidence,result) VALUES($1,$2,$3,$4,$5)",[id,a.vendor?.name||"Unspecified",a.vendor?.url||null,a._evidence||"",JSON.stringify(a)]);return id;}
export async function saveLead(x){const p=getPool();if(!p)return null;const id=crypto.randomUUID();await p.query("INSERT INTO leads(id,name,email,company,role,source,assessment_id,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8)",[id,x.name||null,x.email,x.company||null,x.role||null,x.source||"assessment",x.assessmentId||null,JSON.stringify(x.metadata||{})]);return id;}
export async function getAssessment(id){const p=getPool();if(!p)return null;const r=await p.query("SELECT id,created_at,vendor_name,vendor_url,result FROM assessments WHERE id=$1",[id]);return r.rows[0]||null;}
export function storageConfigured(){return !!process.env.DATABASE_URL;}